### ISSUE TITLE
Strange issue with Force Power Upgrades

### ISSUE THREAD

**Issue by sparkertime** [citizenparker/swsheets#84]
A few instances of this from the production app logs

```
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Ecto.Changeset.cast/4
        (ecto) lib/ecto/changeset.ex:186: Ecto.Changeset.cast(nil, %{"description" =>
"Enhance can be used with the Coordination skill. ", "display_order" => "1", "force_po
wer_upgrades" => %{"0" => %{"description" => nil, "display_order" => "0", "id" => nil,
 "name" => nil}}, "id" => "1452", "name" => "control (Coordination)"}, [], ["character
_id", "name", "description", "display_order"])
        (edge_builder) web/controllers/character_controller.ex:173: anonymous fn/2 in
EdgeBuilder.CharacterController.force_power_changesets/2
        (elixir) lib/enum.ex:977: anonymous fn/3 in Enum.map/2
        (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
        (elixir) lib/enum.ex:977: Enum.map/2
        (edge_builder) web/controllers/character_controller.ex:172: EdgeBuilder.Charac
terController.force_power_changesets/2
        (edge_builder) web/controllers/character_controller.ex:101: EdgeBuilder.Charac
terController.update/2
        (edge_builder) web/controllers/character_controller.ex:1: EdgeBuilder.Characte
rController.phoenix_controller_pipeline/2
```

I'm not entirely sure what the issue is here. It looks like we might be trying to update a force power which isn't associated with the user? That first argument into `cast/4` being `nil` is pretty nutty.

**Comment by duffn** [comment]
I haven’t seen this error since adding Sentry. I’ll reopen if it occurs again.
